"""Visuals for 001-hello-world, generated by RUNNING the tutorial's own values.

Comprehension goal: a beginner should leave knowing three mechanics, not three sentences.
  1. print() -> something appears           (cause and effect)
  2. a variable is a labeled box            (the narration says this; show it)
  3. {name} is REPLACED by the value        (the one idea beginners actually stumble on)

Every string below is evaluated here, so the diagram can never drift from what the code prints.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "tools"))
import diagrams as D  # noqa: E402

ART = Path(__file__).parent / "artifacts"
ART.mkdir(exist_ok=True)

# ---- the tutorial's real values, executed here (not retyped) --------------------------------
name = "Python"
version = 3.12
welcome = f"Welcome to {name}"                 # the actual interpolation
learning = f"You're learning Python {version}"

# 1. the variable as the labeled box the narration describes
D.variable_box(ART / "var_box.png", "name", name,
               title="a variable is a labeled box",
               note="put a value in once, reuse it by name")

# 2. the substitution — the moment {name} becomes its value
D.substitution(ART / "fstring.png", 'f"Welcome to {name}"', "{name}", name, welcome,
               title="the f-string swap",
               note="the braces are replaced the moment the line runs")

# 3. same mechanic, a number this time — repetition is what makes it stick
D.substitution(ART / "fstring_num.png", 'f"...Python {version}"', "{version}", version, learning,
               title="it works for numbers too",
               note="any value, not just text")

print("wrote", *(p.name for p in sorted(ART.glob("*.png"))))
