"""paper-verify — the ONE agent that PROVES the source papers match our training data (user 2026-07-12:
"everything we need to verify paper with our data ... with one agent").

The competition data is carved from ZEBRAHUB (Lange et al., Cell 2024, doi 10.1016/j.cell.2024.09.047) and its
ground-truth tracking annotation is generated by the ULTRACK dual-channel sparse-labeling protocol (Royer et al.,
Nat. Methods 2025, PMC12615266 — OPEN ACCESS, read verbatim via research-search `fulltext`). This agent encodes
each falsifiable CLAIM from those papers together with its SOURCE citation, MEASURES the claim against our own
data artifacts (results/label_selection/*.parquet — Cellpose detections + GT lineage stats over all 199 movies),
and returns a MATCH / PARTIAL / MISMATCH verdict per claim. Verdict table + figure cached in detail so we never
re-derive it. Pure `verify_claims()` is data-wise tested (no I/O).

Why some claims are PARTIAL, not MATCH: our movies are the EARLY, sparser sub-window of the paper's full
10 hpf–10 dpf range, and the sparse "platinum" lineages under-sample the many divisions the tissue actually
undergoes — both are real, quantified facts that shape strategy (detection is the lever; the +0.1 division term
has only modest headroom because the GT itself annotates few divisions)."""
from __future__ import annotations
import json
from .base import BaseAgent, COMP

# Each claim: id, human text, paper + citation, the measurement KEY it is judged on, and a pure rule(measure)->
# (verdict, our_data_str). Keeping the rule as data (a lambda over the measurement dict) makes verify_claims pure
# and unit-testable with synthetic measurements.
CELL = "Zebrahub — Lange et al., Cell 2024 (doi 10.1016/j.cell.2024.09.047)"
ULTRACK = "Ultrack — Royer et al., Nat. Methods 2025 (PMC12615266, OA)"


def label_facts():
    """SINGLE SOURCE OF TRUTH for the CONFIRMED label-selection facts + strategic implications, so every decision
    agent (detector-select, arch-builder, math-master, campaign, xai) operates on the SAME 100%-confirmed
    understanding instead of re-deriving it (user 2026-07-12: 'is it 100% matched with select agent, math...').
    Reads the cached paper-verify verdicts if present. Confirmed from Ultrack (PMC12615266) + Zebrahub (Cell 2024);
    full write-up in experiments/eda/eda.md §16."""
    import json
    verdicts = None
    try:
        p = COMP / "results" / "label_selection" / "paper_verify.json"
        if p.exists():
            verdicts = {v["id"]: v["verdict"] for v in json.loads(p.read_text()).get("verdicts", [])}
    except Exception:  # noqa: BLE001
        pass
    return {
        "confirmed": True,
        "source": f"{CELL}; {ULTRACK}",
        "protocol": ("dual-channel sparse MOSAIC labeling: ubiquitous green H2B-mNeonGreen (EVERY nucleus = our "
                     "image) + random ~20–30% mCherry (Tol2 mosaic, clonally inherited) → Ultrack auto-track + "
                     "manual curation into 'platinum' lineages = GT. Isolation is a SIDE-EFFECT of sparsity, "
                     "NOT an annotator criterion."),
        "verdicts": verdicts,        # {'C1':'MATCH',...} once paper-verify has run
        "implications": {
            "detect_all_nuclei": ("labels are REPRESENTATIVE RANDOM mosaic nuclei → detect EVERY nucleus; the "
                                  "sparse GT never rewards a special 'trackable-cell' detector. Node recall is THE lever."),
            "recall_tilt": ("recall-tilted, STAGE/density-adaptive detector; FPs on unlabeled cells are free "
                            "(metric scores only tracked lineages)."),
            "cv_over_credits_easy": ("curation kept 'green-overlapping, easier-to-track' cells → CV recall "
                                     "OVER-estimates real dense-stage (S3–S4) recall. Trust CV for same-detector "
                                     "tweaks; final judge = Kaggle LB. Weight/stratify CV by stage."),
            "div_term_thin": ("GT UNDER-samples divisions (~0.066/track) → the +0.1 division term has only modest "
                              "headroom; prioritize node recall over division modelling."),
            "tissue_agnostic": ("geff nodes carry only t,x,y,z — tissue types (CNS/notochord/…) are scRNA-seq, NOT "
                                "our GT and NOT the label criterion. Do not model tissue type."),
            "generalization_axis": ("generalisation axis is STAGE, not embryo; density 3.8k–79k cells/frame is "
                                    "fully in-domain."),
        },
    }


def verify_claims(m):
    """PURE (data-wise tested): given a measurements dict, return the verdict table. No file I/O — run() supplies
    `m` from our parquet artifacts, the test supplies synthetic values."""
    def V(ok, partial=False):
        return "MATCH" if ok else ("PARTIAL" if partial else "MISMATCH")
    rows = []

    # C1 — cell number increases with developmental time (Zebrahub time-course).
    cps = m.get("cells_per_frame_by_stage", {})
    seq = [cps.get(s) for s in ("S0", "S1", "S2", "S3", "S4") if cps.get(s) is not None]
    mono = len(seq) >= 3 and all(seq[i] < seq[i + 1] for i in range(len(seq) - 1))
    rows.append(dict(id="C1", claim="Cell number rises monotonically with developmental time", source=CELL,
                     paper_says="continuous time-course, embryo grows",
                     our_data=f"cells/frame S0→S4 = {'→'.join(str(int(x)) for x in seq)} ({(seq[-1]/seq[0]):.1f}×)"
                     if seq else "n/a", verdict=V(mono)))

    # C2 — imaging spans the 10 hpf–10 dpf window. Our movies are the EARLY sub-window (a subset, not the whole).
    lo, hi = m.get("cells_per_frame_min"), m.get("cells_per_frame_max")
    rows.append(dict(id="C2", claim="Developmental window 10 hpf–10 dpf", source=CELL,
                     paper_says="whole atlas 10 hpf→10 dpf",
                     our_data=f"our movies cells/frame {int(lo)}–{int(hi)} → early somitogenesis sub-window",
                     verdict=V(False, partial=True)))   # PARTIAL by design: our data = early subset

    # C3 — the embryo undergoes many divisions; images show frequent mitoses.
    ndiv = m.get("total_div", 0); movies_div = m.get("movies_with_div", 0); nmov = m.get("n_movies", 199)
    dpt = m.get("div_per_track", 0.0)
    rows.append(dict(id="C3", claim="Frequent cell divisions across the tissue", source=CELL,
                     paper_says="many mitoses, esp. earlier stages",
                     our_data=f"{ndiv} divisions in GT, {movies_div}/{nmov} movies ≥1, but only "
                              f"{dpt:.3f}/track — sparse GT UNDER-samples divisions",
                     # PARTIAL: divisions are real in the tissue but the sparse 'platinum' lineages annotate few
                     # → the +0.1 division term has only modest headroom (not a mismatch, an under-sampling).
                     verdict=("PARTIAL" if ndiv > 0 else "MISMATCH")))

    # C4 — GT = sparse subset via dual-channel labeling; continuous, complete, curated lineages.
    frac = m.get("label_pct", 0.0); gap = m.get("gap_frac", 0.0)
    rows.append(dict(id="C4", claim="GT = sparse dual-channel 'platinum' lineages (auto-track + curate)",
                     source=ULTRACK, paper_says="20–30% mCherry mosaic → curated long lineages",
                     our_data=f"~{frac:.1f}% of cells labeled, gap_frac={gap:.2f} (continuous), complete tracks",
                     verdict=V(frac < 20 and gap < 0.02)))

    # C5 — the sparse channel is 'consistently easier to track' (less dense) → labeled cells in less-crowded space.
    d_dens = m.get("local_density_cohens_d")
    rows.append(dict(id="C5", claim="Sparse-labeled cells sit in LESS-crowded regions (easier to track)",
                     source=ULTRACK, paper_says="'sparse channel consistently easier to track'",
                     our_data=(f"local-density Cohen's d = {d_dens:+.2f} (labeled < unlabeled)"
                               if d_dens is not None else "n/a"),
                     verdict=V(d_dens is not None and d_dens < -0.1)))

    # C6 — curation kept long, high-quality lineages (few divisions per track).
    span = m.get("median_span", 0.0)
    rows.append(dict(id="C6", claim="Curation kept long high-quality lineages", source=ULTRACK,
                     paper_says="'selecting long... high-quality lineages'",
                     our_data=f"median track span {span:.0f} frames, div/track {dpt:.3f}",
                     verdict=V(span >= 20 and dpt < 0.2)))
    return rows


def _measure():
    """Read our data artifacts → the measurement dict consumed by verify_claims. All numbers come from the
    cached label-selection parquets (Cellpose detections + GT lineage stats over ALL 199 movies)."""
    import pandas as pd
    R = COMP / "results" / "label_selection"
    ad = pd.read_parquet(R / "annotation_detail.parquet")
    st = pd.read_parquet(R / "dataset_zf_stage.parquet")
    cells = pd.read_parquet(R / "cells_cellpose_diverse.parquet")
    # local-density discriminant (labeled vs unlabeled), sanitized like the XAI path
    import numpy as np
    ld = cells[["local_density", "labeled"]].replace([np.inf, -np.inf], np.nan).dropna()
    a = ld[ld.labeled == 1]["local_density"]; b = ld[ld.labeled == 0]["local_density"]
    sp = (((len(a) - 1) * a.std(ddof=1) ** 2 + (len(b) - 1) * b.std(ddof=1) ** 2)
          / max(len(a) + len(b) - 2, 1)) ** 0.5
    d_dens = float((a.mean() - b.mean()) / sp) if sp else None
    return {
        "cells_per_frame_by_stage": st.groupby("stage")["cells_per_frame"].mean().round(0).to_dict(),
        "cells_per_frame_min": float(st.cells_per_frame.min()),
        "cells_per_frame_max": float(st.cells_per_frame.max()),
        "total_div": int(ad.n_div.sum()), "movies_with_div": int((ad.n_div >= 1).sum()),
        "n_movies": int(len(ad)), "div_per_track": float(ad.div_per_track.mean()),
        "label_pct": float(cells.labeled.mean() * 100), "gap_frac": float(ad.gap_frac.mean()),
        "median_span": float(ad.median_span.mean()), "local_density_cohens_d": d_dens,
    }


def _render_table(rows, out_png):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    col = {"MATCH": "#2e7d32", "PARTIAL": "#b8860b", "MISMATCH": "#c0392b"}
    fig, ax = plt.subplots(figsize=(11.5, 0.62 * len(rows) + 1.1)); ax.axis("off")
    ax.set_title("Paper ↔ our training data — claim verification", fontsize=12, loc="left", weight="bold")
    y = len(rows)
    for r in rows:
        y -= 1
        ax.add_patch(plt.Rectangle((0.005, y + 0.12), 0.055, 0.76, fc=col[r["verdict"]], alpha=.9))
        ax.text(0.0325, y + 0.5, r["id"], ha="center", va="center", color="#fff", fontsize=9, weight="bold")
        ax.text(0.075, y + 0.66, r["claim"], fontsize=9.3, weight="bold", va="center")
        ax.text(0.075, y + 0.30, f"paper: {r['paper_says']}   ·   ours: {r['our_data']}",
                fontsize=8.1, color="#444", va="center")
        ax.text(0.995, y + 0.5, r["verdict"], ha="right", va="center", fontsize=9.2,
                color=col[r["verdict"]], weight="bold")
    ax.set_xlim(0, 1); ax.set_ylim(0, len(rows))
    fig.tight_layout(); fig.savefig(out_png, dpi=130, bbox_inches="tight"); plt.close(fig)


class PaperVerify(BaseAgent):
    name = "paper-verify"
    thread = "V"
    kind = "verdict"

    def run(self, q, worker):
        spec = self.spec(q)
        m = spec.get("measurements")                        # allow injected measurements (test/reuse)
        if not m:
            try:
                m = _measure()
            except Exception as e:  # noqa: BLE001 — missing/unreadable label-selection parquets → clean escalate
                return self.escalate(worker, "leader", f"[{worker}] paper-verify: cannot read label-selection "
                                     f"artifacts ({type(e).__name__}: {str(e)[:100]}). Run label-selection first "
                                     "or pass spec['measurements'].")
        rows = verify_claims(m)
        R = COMP / "results" / "label_selection"; R.mkdir(parents=True, exist_ok=True)
        figs = R / "figs"; figs.mkdir(parents=True, exist_ok=True)
        png = figs / "paper_verify_table.png"
        try:
            _render_table(rows, png)
        except Exception:  # noqa: BLE001
            png = None
        if png is not None:                                 # mirror to a hub-SERVED dir (results/ is /asset-excluded)
            import shutil
            served = COMP / "learning" / "label_figs"; served.mkdir(parents=True, exist_ok=True)
            try:
                shutil.copyfile(png, served / png.name)
            except Exception:  # noqa: BLE001
                pass
        import pandas as pd
        pd.DataFrame(rows).to_parquet(R / "paper_verify.parquet")
        (R / "paper_verify.json").write_text(json.dumps({"measurements": m, "verdicts": rows}, indent=2,
                                                        default=str))
        n_match = sum(1 for r in rows if r["verdict"] == "MATCH")
        n_part = sum(1 for r in rows if r["verdict"] == "PARTIAL")
        tbl = "; ".join(f"{r['id']}:{r['verdict']}" for r in rows)
        summary = (f"paper-verify: {n_match}/{len(rows)} MATCH, {n_part} PARTIAL vs Zebrahub(Cell 2024)+"
                   f"Ultrack(PMC12615266). {tbl}. Cached → results/label_selection/paper_verify.parquet")
        self.log(summary, kind="verdict",
                 recommendation="the PARTIALs are informative, not failures: our data is the EARLY sub-window "
                                "(C2) and the sparse GT under-samples divisions (C3) → detection is the lever; the "
                                "+0.1 division term has only modest headroom. Figures for /learn cached.")
        return self.done({"verdicts": rows, "measurements": m, "n_match": n_match, "n_partial": n_part,
                          "figure": str(png) if png else None}, summary)


_AGENT = PaperVerify()


def run(q, worker):
    return _AGENT.run(q, worker)
